local database =
{
    [4] = {
        [24]   = {['name']="Dia II",                         ['category']=4,  ['id']=24,   ['animation']=24,   ['message']=2,   },
        [50]   = {['name']="Shell III",                      ['category']=4,  ['id']=50,   ['animation']=50,   ['message']=230, },
        [53]   = {['name']="Blink",                          ['category']=4,  ['id']=53,   ['animation']=53,   ['message']=230, },
        [54]   = {['name']="Stoneskin",                      ['category']=4,  ['id']=54,   ['animation']=54,   ['message']=230, },
        [55]   = {['name']="Aquaveil",                       ['category']=4,  ['id']=55,   ['animation']=55,   ['message']=230, },
        [57]   = {['name']="Haste",                          ['category']=4,  ['id']=57,   ['animation']=57,   ['message']=230, },
        [147]  = {['name']="Fire IV",                        ['category']=4,  ['id']=147,  ['animation']=147,  ['message']=2,   },
        [152]  = {['name']="Blizzard IV",                    ['category']=4,  ['id']=152,  ['animation']=152,  ['message']=2,   },
        [157]  = {['name']="Aero IV",                        ['category']=4,  ['id']=157,  ['animation']=157,  ['message']=2,   },
        [167]  = {['name']="Thunder IV",                     ['category']=4,  ['id']=167,  ['animation']=167,  ['message']=2,   },
        [196]  = {['name']="Thundaga III",                   ['category']=4,  ['id']=196,  ['animation']=196,  ['message']=2,   },
        [197]  = {['name']="Thundaga IV",                    ['category']=4,  ['id']=197,  ['animation']=197,  ['message']=2,   },
        [213]  = {['name']="Burst II",                       ['category']=4,  ['id']=213,  ['animation']=213,  ['message']=2,   },
        [226]  = {['name']="Poisonga II",                    ['category']=4,  ['id']=226,  ['animation']=226,  ['message']=236, },
        [235]  = {['name']="Burn",                           ['category']=4,  ['id']=235,  ['animation']=235,  ['message']=237, },
        [237]  = {['name']="Choke",                          ['category']=4,  ['id']=237,  ['animation']=237,  ['message']=237, },
        [247]  = {['name']="Aspir",                          ['category']=4,  ['id']=247,  ['animation']=247,  ['message']=228, },
        [249]  = {['name']="Blaze Spikes",                   ['category']=4,  ['id']=249,  ['animation']=249,  ['message']=230, },
        [252]  = {['name']="Stun",                           ['category']=4,  ['id']=252,  ['animation']=252,  ['message']=236, },
        [253]  = {['name']="Sleep",                          ['category']=4,  ['id']=253,  ['animation']=253,  ['message']=236, },
        [274]  = {['name']="Sleepga II",                     ['category']=4,  ['id']=274,  ['animation']=270,  ['message']=236, },
        [376]  = {['name']="Horde Lullaby",                  ['category']=4,  ['id']=376,  ['animation']=376,  ['message']=85,  },
        [392]  = {['name']="Knight\'s Minne IV",             ['category']=4,  ['id']=392,  ['animation']=391,  ['message']=230, },
        [397]  = {['name']="Valor Minuet IV",                ['category']=4,  ['id']=397,  ['animation']=396,  ['message']=230, },
        [420]  = {['name']="Victory March",                  ['category']=4,  ['id']=420,  ['animation']=435,  ['message']=230, },
        [421]  = {['name']="Battlefield Elegy",              ['category']=4,  ['id']=421,  ['animation']=436,  ['message']=85,  },
        [425]  = {['name']="Dextrous Etude",                 ['category']=4,  ['id']=425,  ['animation']=440,  ['message']=230, },
        [462]  = {['name']="Magic Finale",                   ['category']=4,  ['id']=462,  ['animation']=461,  ['message']=85,  },
    },
}
return database